
#MotorFactory 2019.1.0
#Updater_All

import aqDsl 
import smPmIr3Dsl
#2020/10/17 12:56:03 IST
#Shyamanth R H
aqDsl.updatePreferedMaterials(conductor="REF.Copper",fluid="REF.Air",insulator="REF.Nomex_130",lamination="REF.M330_35A",magnet="REF.SmCo_1040_1800",solid="REF.EN_1_1151")
smPmIr3Dsl.newMotor(machineType=smPmIr3Dsl.MachineTypeEnum.SM_PMM_INNERROT_3PH,motorName="NewMotor1")
smPmIr3Dsl.saveAsMotorFromfolderToCatalog(catalogName="User_SM_PM_IR_3Ph",motorName="Test_Motor",eraseOld=False)
#2020/10/17 14:55:00 IST
#Shyamanth R H
aqDsl.updatePreferedMaterials(conductor="REF.Copper",fluid="REF.Air",insulator="REF.Nomex_130",lamination="REF.M330_35A",magnet="REF.SmCo_1040_1800",solid="REF.EN_1_1151")
#smPmIr3Dsl.openMotor(catalogName="User_SM_PM_IR_3Ph",motorName="Test_Motor")
#2020/10/23 18:03:22 IST
#Shyamanth R H
aqDsl.updatePreferedMaterials(conductor="REF.Copper",fluid="REF.Air",insulator="REF.Nomex_130",lamination="REF.M330_35A",magnet="REF.SmCo_1040_1800",solid="REF.EN_1_1151")
#smPmIr3Dsl.openMotor(catalogName="User_SM_PM_IR_3Ph",motorName="Test_Motor")
smPmIr3Dsl.changeMagnet(libraryName="imi_Block",partName="imi_Block_02B")
smPmIr3Dsl.changeMagnetParameter(parameters={"WM":0.012})
smPmIr3Dsl.changeMagnetParameter(parameters={"TM":0.006})
smPmIr3Dsl.changeInputDimensionMode(inputDimensionMode=smPmIr3Dsl.InputDimensionMode.ROTOR_OUTER_DIAMETER)
smPmIr3Dsl.changeInputDimensionMode(inputDimensionMode=smPmIr3Dsl.InputDimensionMode.STATOR_INNER_DIAMETER)
smPmIr3Dsl.changeInputDimensionMode(inputDimensionMode=smPmIr3Dsl.InputDimensionMode.ROTOR_OUTER_DIAMETER)
smPmIr3Dsl.changeLamination(type=smPmIr3Dsl.LaminationEnum.RECTANGULAR_RIGHT)
smPmIr3Dsl.changeLamination(type=smPmIr3Dsl.LaminationEnum.RECTANGULAR_CHAMFERED)
smPmIr3Dsl.changeLamination(type=smPmIr3Dsl.LaminationEnum.RECTANGULAR_ROUNDED)
smPmIr3Dsl.changeLaminationParameter(parameters={"R":0.01})
smPmIr3Dsl.changeHousing(type=smPmIr3Dsl.HousingEnum.RECTANGULAR)
smPmIr3Dsl.changeHousing(type=smPmIr3Dsl.HousingEnum.NONE)
smPmIr3Dsl.editMotor(airgapLength=8.0E-4,noStatorSlots=24,rotorInnerDiameter=0.02,rotorLength=0.12,statorInnerDiameter=0.06,statorLength=0.12,statorOuterDiameter=0.11)
smPmIr3Dsl.changeShaft(type=smPmIr3Dsl.ShaftEnum.SOLID)
smPmIr3Dsl.changeShaftParameter(parameters={"D1":0.012,"D2":0.012,"L1":0.025,"L2":0.025})
smPmIr3Dsl.changeMaterial(materials={"magneticCircuit":"REF.M400_65A","magnets":"REF.NdFeB_1320_1400"},target=smPmIr3Dsl.MotorMaterialObjectEnum.ROTOR)
smPmIr3Dsl.changeSlot(libraryName="os_Free",partName="os_Free_03C")
smPmIr3Dsl.startMacroTransaction()
smPmIr3Dsl.changeWindingCoil(noWiresInHand=1,wireDiameter=0.0023271297410356407)
smPmIr3Dsl.changeWindingInsulationThickness(wire=6.95671579628602E-5)
smPmIr3Dsl.endMacroTransaction()
smPmIr3Dsl.runTest(testType="STAT_SINEWAVE_TORQUESPEED")
smPmIr3Dsl.changeCharOpencircuitCoggingParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.runTest(testType="CHAR_OPENCIRCUIT_COGGING")
smPmIr3Dsl.runTest(testType="CHAR_OPENCIRCUIT_BACKEMF")
smPmIr3Dsl.changeCharOpencircuitBackemfParameter(speed=1884.9555921538758)
smPmIr3Dsl.runTest(testType="CHAR_OPENCIRCUIT_BACKEMF")
smPmIr3Dsl.runTest(testType="CHAR_OPENCIRCUIT_BACKEMF")
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED,maximumSpeed=1884.9555921538758)
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.runTest(testType="STAT_SINEWAVE_TORQUESPEED")
smPmIr3Dsl.editMotor(rotorLength=0.04,statorLength=0.04)
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.runTest(testType="STAT_SINEWAVE_TORQUESPEED")
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED,userWorkingPointAnalysis=smPmIr3Dsl.UserWPAnalysisEnum.SINGLE,userWorkingPointSpeed=1884.9555921538758,userWorkingPointTorque=0.3)
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.runTest(testType="STAT_SINEWAVE_TORQUESPEED")
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.runTest(testType="STAT_SINEWAVE_TORQUESPEED")
smPmIr3Dsl.changeMagnetParameter(parameters={"TM":0.005,"WM":0.01})
smPmIr3Dsl.editMotor(rotorLength=0.02,statorLength=0.02)
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.runTest(testType="STAT_SINEWAVE_TORQUESPEED")
smPmIr3Dsl.setEasyWinding()
smPmIr3Dsl.setAutomaticWinding()
smPmIr3Dsl.startMacroTransaction()
smPmIr3Dsl.changeWindingCoil(noTurnsPerCoil=80,wireDiameter=0.0082525)
smPmIr3Dsl.changeWindingInsulationThickness(wire=4.122726829675189E-5)
smPmIr3Dsl.endMacroTransaction()
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
#error while executing :
#smPmIr3Dsl.runTest(testType="STAT_SINEWAVE_TORQUESPEED")
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED,userWorkingPointAnalysis=smPmIr3Dsl.UserWPAnalysisEnum.NONE)
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
#error while executing :
#smPmIr3Dsl.runTest(testType="STAT_SINEWAVE_TORQUESPEED")
smPmIr3Dsl.changeStatSinewaveTorquespeedGeneratorParameter(maximumSpeed=1884.9555921538758)
smPmIr3Dsl.changeStatSinewaveTorquespeedGeneratorParameter(userWorkingPointAnalysis=smPmIr3Dsl.UserWPAnalysisEnum.SINGLE,userWorkingPointSpeed=1884.9555921538758,userWorkingPointTorque=0.3)
smPmIr3Dsl.runTest(testType="PERF_SINEWAVE_GENERATOR_EFFICIENCYMAP")
smPmIr3Dsl.startMacroTransaction()
smPmIr3Dsl.changeWindingCoil(noTurnsPerCoil=30,wireDiameter=0.0011241104604869912)
smPmIr3Dsl.changeWindingInsulationThickness(wire=5.208499203074961E-5)
smPmIr3Dsl.endMacroTransaction()
smPmIr3Dsl.runTest(testType="PERF_SINEWAVE_GENERATOR_EFFICIENCYMAP")
smPmIr3Dsl.startMacroTransaction()
smPmIr3Dsl.changeWindingCoil(noTurnsPerCoil=60,wireDiameter=7.94866129413084E-4)
smPmIr3Dsl.changeWindingInsulationThickness(wire=4.426011360087364E-5)
smPmIr3Dsl.endMacroTransaction()
smPmIr3Dsl.setAutomaticWinding(noParallelPaths=4)
smPmIr3Dsl.runTest(testType="PERF_SINEWAVE_GENERATOR_EFFICIENCYMAP")
smPmIr3Dsl.changeWindingCoil(noTurnsPerCoil=300)
smPmIr3Dsl.runTest(testType="PERF_SINEWAVE_GENERATOR_EFFICIENCYMAP")
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.runTest(testType="STAT_SINEWAVE_TORQUESPEED")
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED,maximumLineLineVoltage=240.0)
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.runTest(testType="STAT_SINEWAVE_TORQUESPEED")
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED,userWorkingPointAnalysis=smPmIr3Dsl.UserWPAnalysisEnum.SINGLE,userWorkingPointSpeed=1884.9555921538758,userWorkingPointTorque=0.3)
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.runTest(testType="STAT_SINEWAVE_TORQUESPEED")
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.runTest(testType="STAT_SINEWAVE_TORQUESPEED")
smPmIr3Dsl.saveMotor()
smPmIr3Dsl.changeWindingCoil(noTurnsPerCoil=100)
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.runTest(testType="STAT_SINEWAVE_TORQUESPEED")
smPmIr3Dsl.runTest(testType="CHAR_OPENCIRCUIT_BACKEMF")
smPmIr3Dsl.changeWindingCoil(noTurnsPerCoil=200)
smPmIr3Dsl.runTest(testType="CHAR_OPENCIRCUIT_BACKEMF")
smPmIr3Dsl.changeWindingCoil(noTurnsPerCoil=250)
smPmIr3Dsl.runTest(testType="CHAR_OPENCIRCUIT_BACKEMF")
smPmIr3Dsl.changeWindingCoil(noTurnsPerCoil=240)
smPmIr3Dsl.runTest(testType="CHAR_OPENCIRCUIT_BACKEMF")
smPmIr3Dsl.changeStatSquarewaveWorkingpointCurrentdrivenParameter(speed=1884.9555921538758)
smPmIr3Dsl.runTest(testType="WP_SQUARE_MOT_CURRENT")
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.changeStatSinewaveTorquespeedParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED)
smPmIr3Dsl.runTest(testType="STAT_SINEWAVE_TORQUESPEED")
smPmIr3Dsl.changeCharDatasheetMotorParameter(displayMode=smPmIr3Dsl.ParameterDisplayEnum.ADVANCED,maximumLineLineVoltage=240.0)
smPmIr3Dsl.runTest(testType="CHAR_DATASHEET_MOTOR")
smPmIr3Dsl.resetTestParameter(testType="CHAR_DATASHEET_MOTOR")
smPmIr3Dsl.changeCharModelMapsParameter(maximumSpeed=1884.9555921538758)
smPmIr3Dsl.runTest(testType="CHAR_MODEL_MAPS")
smPmIr3Dsl.runTest(testType="CHAR_OPENCIRCUIT_BACKEMF")
smPmIr3Dsl.changeCharDatasheetMotorParameter(currentDefinitionMode=smPmIr3Dsl.CurrentModeEnum.CURRENT,maximumLineCurrent=1.8,maximumLineLineVoltage=240.0)
smPmIr3Dsl.runTest(testType="CHAR_DATASHEET_MOTOR")
smPmIr3Dsl.startMacroTransaction()
smPmIr3Dsl.changeWindingCoil(noTurnsPerCoil=250,wireDiameter=3.894032861766231E-4)
smPmIr3Dsl.changeWindingInsulationThickness(wire=3.064219740543473E-5)
smPmIr3Dsl.endMacroTransaction()
smPmIr3Dsl.runTest(testType="CHAR_DATASHEET_MOTOR")
smPmIr3Dsl.changeCharDatasheetMotorParameter(maximumLineCurrent=1.728)
smPmIr3Dsl.runTest(testType="CHAR_DATASHEET_MOTOR")
smPmIr3Dsl.changeWindingCoil(noTurnsPerCoil=280)
smPmIr3Dsl.runTest(testType="CHAR_DATASHEET_MOTOR")
smPmIr3Dsl.changeWindingCoil(noTurnsPerCoil=200)
smPmIr3Dsl.runTest(testType="CHAR_DATASHEET_MOTOR")
smPmIr3Dsl.saveMotor()
smPmIr3Dsl.changeLamination(type=smPmIr3Dsl.LaminationEnum.RECTANGULAR_CHAMFERED)
smPmIr3Dsl.changeLaminationParameter(parameters={"L":0.01})
smPmIr3Dsl.changeLamination(type=smPmIr3Dsl.LaminationEnum.RECTANGULAR_ROUNDED)
smPmIr3Dsl.changeLaminationParameter(parameters={"R":0.01})
smPmIr3Dsl.saveMotor()
smPmIr3Dsl.storeMotor(catalogName="User_SM_PM_IR_3Ph",motorName="Test_Motor_1",eraseOld=False)
smPmIr3Dsl.saveMotor()
#2020/10/24 11:04:54 IST
#Shyamanth R H
aqDsl.updatePreferedMaterials(conductor="REF.Copper",fluid="REF.Air",insulator="REF.Nomex_130",lamination="REF.M330_35A",magnet="REF.SmCo_1040_1800",solid="REF.EN_1_1151")
#smPmIr3Dsl.openMotor(catalogName="User_SM_PM_IR_3Ph",motorName="Test_Motor")
smPmIr3Dsl.saveMotor()
